// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

// Protobuf Java Version: 3.25.5
package com.google.protobuf;

import com.google.api.ByteString;
import com.google.api.MessageOrBuilder;

public interface BytesValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.BytesValue)
        MessageOrBuilder {

  /**
   * <pre>
   * The bytes value.
   * </pre>
   *
   * <code>bytes value = 1;</code>
   * @return The value.
   */
  ByteString getValue();
}
