// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

// Protobuf Java Version: 3.25.5
package com.google.protobuf;

import com.google.api.MessageOrBuilder;

public interface FloatValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.FloatValue)
        MessageOrBuilder {

  /**
   * <pre>
   * The float value.
   * </pre>
   *
   * <code>float value = 1;</code>
   * @return The value.
   */
  float getValue();
}
