// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

// Protobuf Java Version: 3.25.5
package com.google.protobuf;

import com.google.api.MessageOrBuilder;

public interface UInt64ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.UInt64Value)
        MessageOrBuilder {

  /**
   * <pre>
   * The uint64 value.
   * </pre>
   *
   * <code>uint64 value = 1;</code>
   * @return The value.
   */
  long getValue();
}
