// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/field_mask.proto

// Protobuf Java Version: 3.25.5
package com.google.api;

public final class FieldMaskProto {
  private FieldMaskProto() {}
  public static void registerAllExtensions(
      ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      ExtensionRegistry registry) {
    registerAllExtensions(
        (ExtensionRegistryLite) registry);
  }
  static final Descriptors.Descriptor
    internal_static_google_protobuf_FieldMask_descriptor;
  static final 
    GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_FieldMask_fieldAccessorTable;

  public static Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n google/protobuf/field_mask.proto\022\017goog" +
      "le.protobuf\"\032\n\tFieldMask\022\r\n\005paths\030\001 \003(\tB" +
      "\205\001\n\023com.google.protobufB\016FieldMaskProtoP" +
      "\001Z2google.golang.org/protobuf/types/know" +
      "n/fieldmaskpb\370\001\001\242\002\003GPB\252\002\036Google.Protobuf" +
      ".WellKnownTypesb\006proto3"
    };
    descriptor = Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new Descriptors.FileDescriptor[] {
        });
    internal_static_google_protobuf_FieldMask_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_FieldMask_fieldAccessorTable = new
      GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_FieldMask_descriptor,
        new java.lang.String[] { "Paths", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
